[[redirects]]
  from = "*"
  to = "https://www.draw.io/?&p=exlightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=wireframe-with-drawio.html#Uhttps://drive.google.com/uc?id=1xTkpINJZCF6V7drIJ808crwRMbJ4pB8-&export=download"
  status = 301
  force = true
