checkoutLocation: "source"
workspaceLocation: "vscode"
tasks:
    - command: npx paxos-raft
ports:
  - port: 3000-8999
    onOpen: ignore
vscode:
  extensions:
    - paxos-raft.paxos-raft@0.0.87:Roq2YRM1Fk/5uLi75zpm4g==