checkoutLocation: "."
workspaceLocation: "."
tasks:
    - command: cp index.code.md README.md
    - command: npx paxos-raft
ports:
  - port: 2999-8999
    onOpen: ignore
vscode:
  extensions:
    - paxos-raft.paxos-raft@0.0.100:2KVno7cL8wx/tWiYnDgCiA==