checkoutLocation: "."
workspaceLocation: "."
tasks:
    - command: |
      code gitpod.yml  
      npx paxos-raft
ports:
  - port: 2999-8999
    onOpen: ignore
vscode:
  extensions:
    - paxos-raft.paxos-raft@0.0.87:Roq2YRM1Fk/5uLi75zpm4g==