name: Node.js Package

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12  
      - run: npm ci
      - run: npm run lerna:bootstrap 
      - run: npm run lerna:test
       
      - name: Authenticate with Git 
        run: |
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL
          git remote set-url origin https://$GITHUB_ACTOR:$GIT_AUTH_TOKEN@github.com/paxos-raft/paxos-raft
        env:
          USER_EMAIL: ${{secrets.github_email}}
          USER_NAME: ${{secrets.github_user}}
          GIT_AUTH_TOKEN: ${{secrets.github_auth}}

      - name: Checkout and Pull Master
        run: git checkout master && git pull

      - name: Authenticate with Registry
        run: |
          echo "registry=http://registry.npmjs.com/" >> .npmrc
          echo "//registry.npmjs.com/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Publish on Sketch
        run: |
          git reset --hard HEAD
          npm i -g skpm
          skpm publish patch --skip-registry
          git tag -l | head -n 20 git push --delete origin
        env:
          GITHUB_ACCESS_TOKEN: ${{secrets.github_auth}}

      - name: Publish on npm 
        run: |
          git reset --hard HEAD        
          npm run lerna:publish
          git tag -l | head -n 20 git push --delete origin

      - name: Publish on VS Code Marketplace
        run: |
          git reset --hard HEAD
          npm i -g vsce
          vsce publish -p $VSCE_TOKEN patch
          git tag -l | head -n 20 git push --delete origin
        env:
          VSCE_TOKEN: ${{secrets.vsce_token}}
